import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/session-provider";
import { MiniKitProvider } from "@/components/MiniKitProvider";
import { Sora } from "next/font/google";
const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ErudaProvider = dynamic(
    () => import("../components/Eruda").then((c) => c.ErudaProvider),
    {
      ssr: false,
    }
  );
  const session = await getServerSession();

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Mono:ital@0;1&family=Rubik:ital,wght@0,300..900;1,300..900&family=Sora:wght@600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={sora.className}>
        <MiniKitProvider>
          <ErudaProvider>
            <SessionProvider session={session}>{children}</SessionProvider>
          </ErudaProvider>
        </MiniKitProvider>
      </body>
    </html>
  );
}
